/*拖车处理*/
export default [
  {'code': 'trailerNo', 'lable': '拖车单号', 'fixed': 'left', 'width': '120px'},
  {'code': 'caseNo', 'lable': '案件编号', 'linked': true, 'width': '120px', 'fixed': 'left'},
  {'code': 'contractNo', 'lable': '合同编号', 'width': '80px'},
  {'code': 'customerName', 'lable': '客户姓名', 'width': '80px'},
  {'code': 'inputRegion', 'lable': '所属分部',},
  {'code': 'inputOrgid', 'lable': '所属门店', },
  {'code': 'trailerType', 'lable': '拖车类型', },
  {'code': 'trailerPeople', 'lable': '拖车员', 'width': '80px'},
  {'code': 'trailerDeadline', 'lable': '拖车期限', 'width': '80px'},
  {'code': 'plateNumber', 'lable': '车牌号', 'width': '80px'},
  {'code': 'carFrameNumber', 'lable': '车架号', 'width': '80px'},
  {'code': 'carColor', 'lable': '车身颜色', 'width': '80px'},
  {'code': 'trailerStatus', 'lable': '车辆处理状态', 'width': '120px'},
  {'code': 'mainReason', 'lable': '主原因', 'width': '80px'},
  {'code': 'childReason', 'lable': '子原因', 'width': '80px'},
  {'code': 'futurePrice', 'lable': '处理预估价格', 'width': '120px'},
  {'code': 'trailerAddress', 'lable': '实际拖车地', 'width': '120px'},
  {'code': 'fee', 'lable': '费用', 'width': '80px'},
  {'code': 'assessPrice', 'lable': '总部车辆评估价', 'width': '120px'},
  {'code': 'approvalPrice', 'lable': '审批价格', 'width': '80px'},
  {'code': 'actualPrice', 'lable': '车辆处理价', 'width': '120px'},
  {'code': 'updator', 'lable': '处理人', 'width': '80px'},
  {'code': 'updatedTime', 'lable': '处理时间', 'width': '80px'},
]
