export default [
  {'code': 'contractSerialNo', 'lable': '合同编号', 'linked': true, "width": "220px"},
  {'code': 'userName', 'lable': '客户姓名'},
  {'code': 'idCard', 'lable': '身份证号'},
  {'code': 'orgName', 'lable': '门店'},
  {'code': 'inputUser', 'lable': '录入人'},
  {'code': 'recheckUser', 'lable': '复核人'},
  {'code': 'praeiudiciumUser', 'lable': '初审人'},
  {'code': 'finalJudgmentUser', 'lable': '终审人'},
  {'code': 'productName', 'lable': '产品名称'},
  {'code': 'contractAmount', 'lable': '贷款金额','amountFormate':true},
  {'code': 'loanTerm', 'lable': '贷款期限(月)'},
  {'code': 'payAmount', 'lable': '应还总计','amountFormate':true},
  {'code': 'applyReduceSum', 'lable': '减免金额','amountFormate':true},
  {'code': 'payAmountSubamt', 'lable': '实际应扣金额','amountFormate':true},
  {'code': 'repaymentWay', 'lable': '扣款方式'},
  {'code': 'inputDateStr', 'lable': '申请日期'},
  {'code': 'phaseStatusStr', 'lable': '处理状态'},
]
